@ECHO OFF
REM Copyright 1994 by the GNU FORTH Team
ECHO *** Configuring for MS-DOS with DJGPP GNU C ***
COPY MAKEFILE.DOS MAKEFILE
COPY KERNL32L.FI GFORTH.FI
COPY 386.H MACHINE.H
COPY STARTUP.FS STARTUP.UNX
COPY STARTUP.DOS STARTUP.FS
