#! /bin/sh
#script similar to vmgen for  generating some files from prim.b etc.
#Copyright (C) 2001,2002,2003,2007 Free Software Foundation, Inc.

#This file is part of Gforth.

#Gforth is free software; you can redistribute it and/or
#modify it under the terms of the GNU General Public License
#as published by the Free Software Foundation, either version 3
#of the License, or (at your option) any later version.

#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.#See the
#GNU General Public License for more details.

#You should have received a copy of the GNU General Public License
#along with this program; if not, see http://www.gnu.org/licenses/.

#USAGE: GFORTH=... gfgen $TAG
#where $tag is "" or "-fast" depending on what you want to process and generate
TAG=$1
#only files different between gforth and gforth-fast are generated here
$GFORTH prims2x.fs -e "c-flag on s\" prim$TAG.i\" save-mem out-filename 2! s\" prim$TAG.b\" ' output-c ' output-c-combined process-file bye" >engine/prim$TAG.i &&
$GFORTH prims2x.fs -e "c-flag on s\" prim$TAG.b\" ' output-label dup process-file bye" >engine/prim_lab$TAG.i &&
$GFORTH prims2x.fs -e "c-flag on s\" prim$TAG.b\" ' noop dup process-file bye" >engine/prim_grp$TAG.i &&
$GFORTH prims2x.fs -e "c-flag on s\" prim$TAG.b\" ' output-forthname dup process-file bye" >engine/prim_names$TAG.i &&
$GFORTH prims2x.fs -e "c-flag on s\" prim$TAG.b\" ' output-superend dup process-file bye" >engine/prim_superend$TAG.i &&
$GFORTH prims2x.fs -e "c-flag on s\" prim$TAG.b\" ' output-profile ' output-profile-combined process-file bye" >engine/profile$TAG.i &&
$GFORTH prims2x.fs -e "c-flag on s\" prim$TAG.b\" ' output-super2-simple ' output-super2-combined process-file bye" >engine/super2$TAG.i &&
$GFORTH prims2x.fs -e "c-flag on s\" prim$TAG.b\" ' output-costs-gforth-simple ' output-costs-gforth-combined process-file bye" >engine/costs$TAG.i &&
$GFORTH prims2x.fs -e "c-flag on s\" prim$TAG.b\" ' output-c-prim-num ' noop process-file bye" >engine/prim_num$TAG.i
#unused:
#$GFORTH prims2x.fs -e "c-flag on s\" prim$TAG.b\" ' noop ' output-peephole process-file bye" >engine/peephole$TAG.i &&
