.TH GForth 1 "November 27, 1994" \" -*- nroff -*-

.SH NAME

GForth

.SH SYNOPSIS

\fCgforth\fR [initialization options] [image-specific options]

.SH DESCRIPTION

\fBGForth\fR is a fast and portable implementation of the Forth
programming language. For details read the manual.

.SH ENVIRONMENT VARIABLES

\fCGFORTHPATH\fR
gives the search path for source files.

.SH EXAMPLES

\fCgforth\fR

starts the system and goes into interactive mode.

\fCgforth file1 file2 -e bye\fR

loads and interprets the files \fCfile1\fR and \fCfile2\fR, then
exits.

.SH SEE ALSO

The GForth manual is available in hypertext (Info, HTML) and printable
(TeX, PS) forms.

The ANS Forth document (i.e., the standard).

More information on Gforth (e.g., pointers to new versions, to the
manual on the WWW and to papers about Gforth) is available through
\fChttp://www.complang.tuwien.ac.at/projects/forth.html\fR.
