#! /bin/sh
outfile=$1; shift
tmpfile=./temp-image.fi
test x$GFORTH != x || GFORTH=gforth-ditc
$GFORTH --clear-dictionary $* -e "savesystem $tmpfile"1" bye"
$GFORTH --clear-dictionary --offset-image $* -e "savesystem $tmpfile"2" bye"
./gforth -m 100000 -p. -i ./kernel.fi startup.fs  comp-image.fs -e "comp-image $tmpfile"1" $tmpfile"2" $outfile bye"
#gforth-0.2.1 -m 100000  comp-image.fs -e "comp-image $tmpfile"1" $tmpfile"2" $outfile bye"
rm $tmpfile"1" $tmpfile"2"
