#! /bin/sh
if test $# = 0 || test $1 = --help || test $1 = -h; then
  echo "usage: `basename $0` target-name [gforth-options]"
  echo "  environment: GFORTHD: the Gforth binary used (default: gforth-ditc)"
  echo "creates a relocatable image 'target-name'"
  exit 1
fi
outfile=$1; shift
tmpfile=./temp-image.fi
test x$GFORTHD != x || GFORTHD=gforth-ditc
$GFORTHD --clear-dictionary --no-offset-im $* -e "savesystem $tmpfile"1" bye"
$GFORTHD --clear-dictionary --offset-image $* -e "savesystem $tmpfile"2" bye"
$GFORTHD -i kernel.fi startup.fs  comp-image.fs -e "comp-image $tmpfile"1" $tmpfile"2" $outfile bye"
#gforth-0.2.1 -m 100000  comp-image.fs -e "comp-image $tmpfile"1" $tmpfile"2" $outfile bye"
rm $tmpfile"1" $tmpfile"2"
