#! /usr/local/bin/bash
#test dist on all MACHINES given in MACHINES
#usage: MACHINES="..." testall dirs/gforth-version.tar.gz
if test $# = 0; then
  echo "usage: `basename $0` gforth-xxx.tar.gz"
  exit 1
fi
test "x$MACHINES" != x || MACHINES="jupiter pcs d0 mips aertl@fpr.zserv.tuwien.ac.at aertl@stat.zserv.tuwien.ac.at a5 w4.infosys.tuwien.ac.at samhain.ifs.tuwien.ac.at calis a9"
#taken out: hpws03.infosys.tuwien.ac.at aertl@fbma.tuwien.ac.at
for i in $MACHINES
do
	( ssh $i "test -d xxxgforthtest||mkdir xxxgforthtest; cd xxxgforthtest; test -d $i||mkdir $i; rm -rf $i/*"; \
	 scp -pq $1 testdist $i:xxxgforthtest/$i; \
	 ssh $i "cd xxxgforthtest/$i; ./testdist `basename $1`" >$i 2>&1; \
	 echo "$i done" `tail -1 $i`) &
done
wait
echo all done
