#! /bin/sh
#tests that dist works
#usage: testdist gforth-version.tar.gz
#gforth-version.tar.gz must be in the working directory
MACHINE=`hostname`
GFORTH=`basename $1 .tar.gz`
DIR=`pwd`
rm -rf $GFORTH
gunzip -cd $1 | tar xf -
if make --version|grep -q GNU
then
	echo building in build
	chmod -R a-w $GFORTH
	mkdir build
	cd build
	../$GFORTH/configure --prefix=$DIR/install
else
	echo building in $GFORTH
	cd $GFORTH
	./configure --prefix=$DIR/install
fi
make
make check
#gforth locals-test.fs
#gforth test-counted-loops.fs
make install
#make bench
cd ..
install/bin/gforth test/tester.fs test/coretest.fs test/postpone.fs test/dbltest.fs -e bye && echo test ok
chmod -R +w $GFORTH
cd ..
