FROM forthy42/gforth-gui:latest
LABEL maintainer="Bernd Paysan <bernd@net2o.de>"
ENV LANG=C.UTF-8
ENV XAUTHORITY=/home/gforth/.Xauthority

USER root

RUN apk add --no-cache font-noto-all font-noto-cjk font-noto-emoji ttf-font-awesome

COPY pulse-client.conf /etc/pulse/client.conf

USER gforth

RUN mkdir -p /home/gforth/.config

CMD [ "gforth" ]
